[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
ticket_market = "SWNbKRe5RzCYXA2tfrnXyqXR49ebvsEN4xoyHUKXJ4Y"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/home/adish/.config/solana/id.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "mocha -t 1000000 tests/"

[[bin]]
name = "ticket_market"
path = "programs/ticket_market/src/lib.rs"